apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  config.json: |+
    {
        "secureGateway" :{
          "url":"{{ .Values.config.secureGateway.url }}"
        },
        "apiGateway" :{
          "hostUrl": "{{ .Values.config.apiGateway.hostUrl }}",
          "url": "{{ .Values.config.apiGateway.url }}",
          "xibmclientid": "{{ .Values.config.apiGateway.clientid }}"
        },
        "conversationBroker" :{
          "url":"{{ .Values.config.conversationBroker.url }}"
        },
        "advisorBroker": {
          "url": "{{ .Values.config.advisorBroker.url }}"
        },
        "customerAPI":{
              "url":"{{ .Values.config.customerAPI.url }}",
              "host":"{{ .Values.config.customerAPI.host }}"
        },
        "mode" : "{{ .Values.config.mode }}",
        "environment" : "{{ .Values.config.environment }}",
        "port": "{{ .Values.config.port }}",
        "version": "{{ .Values.config.version }}"
    }
